# Generated by Django 2.2.12 on 2020-11-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=23)),
                ('lname', models.CharField(max_length=23)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=32)),
                ('repassword', models.CharField(max_length=32)),
            ],
        ),
    ]
