# Generated by Django 2.2.12 on 2020-11-25 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='repassword',
            new_name='Confirm_password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='fname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lname',
            new_name='lastname',
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
